
# sfft parameters
frequency : 16000
source_frequency : 44100
n_fft : 512
win_size : 0.032
overlap : 0.5
max_audio : 0.200958791215
fixed_audio_length : 4  # audio length, unit second

# netft f/t bias
x: 4.2
y: -25.3
z: 17
# ur5 f/t bias
ur5_x: -5.4747
ur5_y: 5.7189
ur5_z: -53.008

# normalization params
filtered:
    audio_mean : -27.8152
    audio_std : 12.7377
unfiltered:
    audio_mean : -29.5745
    audio_std : 13.0787


# network configs
input_audio_size : 257
input_audio_size_seg : 100
bottle_upper : 150.0
bottle_lower : 0.0
scale_upper : 770.0
scale_lower : 0.0

# cup real height
cup_height_1 : 127
cup_height_3 : 99
cup_height_4 : 150

# topic names
audio_topic : "/portaudio_transport"
ur5_ft_topic : "/robotiq_ft_wrench"
ati_ft_topic : "/netft_data"
scale_topic : "/maul_logic/wrench"
phasespace_topic : "/ps_owl/rigids"

# bottle id list
bottle_id_list : [1, 2, 3, 4, 5, 6]
